### ISSUE TITLE
[error]Could not find any pipeline artifacts in the build.

### ISSUE THREAD

**Issue by gabrielfsousa** [microsoft/azure-pipelines-yaml#198]
i'm using the new multi-stage pipeline with deploy on yaml.
but i have this error..

 

```
##[debug]Evaluating condition for step: 'Download Artifact'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Download Artifact
==============================================================================
Task         : Download Pipeline Artifact
Description  : Download Pipeline Artifact
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : Download named artifact from a pipeline to a local path.
==============================================================================
Download from the specified build: #4537
Download artifact to: /vsts/agent/_work/9/
##[error]Could not find any pipeline artifacts in the build.
##[debug]Processed: ##vso[task.logissue type=error;]Could not find any pipeline artifacts in the build.
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Agent.Plugins.PipelineArtifact.PipelineArtifactServer.DownloadAsync(AgentTaskPluginExecutionContext context, PipelineArtifactDownloadParameters downloadParameters, DownloadOptions downloadOptions, CancellationToken cancellationToken)
   at Agent.Plugins.PipelineArtifact.DownloadPipelineArtifactTaskV1.ProcessCommandInternalAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
```

**Comment by gabrielfsousa** [comment]
found the issue
i was not using the task: PublishPipelineArtifact@0.
i was only using task: PublishBuildArtifacts  ... 

using the old build pipelines i didint need the Pipeline Artifact

**Comment by waterfoul** [comment]
I'm seeing this as well

**Comment by waterfoul** [comment]
switching to using 
```
- upload: '$(Build.ArtifactStagingDirectory)'
  artifact: package
```
fixed it
