### ISSUE TITLE
Inconsistent cache behavior between pipeline and template

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-pipelines-yaml#284]
I had the following code in a self-contained Azure Pipeline (all in one file):

```yaml
- task: CacheBeta@0
  displayName: Cache npm
  condition: variables['IsCacheEnabled']
  inputs:
    key: $(Build.SourcesDirectory)/package-lock.json
    path: $(npm_config_cache)
```

The result was:

```
##[section]Starting: Cache npm
==============================================================================
Task         : Cache (Beta)
Description  : Cache files between runs
Version      : 0.1.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Information, Using the following fingerprint argument (D:\a\1\s/package-lock.json) as a string value.
Information, Generated fingerprint: D25D605C7B30A4E85CF83D2C91A5766FC2CF9EB257A58DFCE5C5F1E1C818CCB700
Information, Getting a pipeline cache artifact with the following fingerprint: D25D605C7B30A4E85CF83D2C91A5766FC2CF9EB257A58DFCE5C5F1E1C818CCB700
Information, There is a cache hit.
Manifest ID is: 240B056E8EF678CA1DB688EFF3577B587593F72A7E97F3B511AE5A103D9AC3C802
Information, DedupManifestArtifactClient will correlate http requests with X-TFS-Session b70dec3e-ae2b-4adf-b335-1833c9e47697
Information, Could not initialize dataport.
Information, Downloaded 0.0 MB out of 54.2 MB (0%).
Information, Downloaded 54.2 MB out of 54.2 MB (100%).
Information, 
Download statistics:
Total Content: 54.2 MB
Physical Content Downloaded: 51.6 MB
Compression Saved: 2.6 MB
Local Caching Saved: 0.0 MB
Chunks Downloaded: 3,510
Nodes Downloaded: 0

Information, Download completed.
Cache restored.
##[section]Finishing: Cache npm
```

Then I moved some later jobs in a separate stage into a template (did not include this step), and got a different result:

```
##[debug]Evaluating condition for step: 'Cache npm'
##[debug]Evaluating: variables['IsCacheEnabled']
##[debug]Evaluating indexer:
##[debug]..Evaluating variables:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'IsCacheEnabled'
##[debug]=> 'true'
##[debug]=> True
##[debug]Expanded: 'true'
##[debug]Result: True
##[section]Starting: Cache npm
==============================================================================
Task         : Cache (Beta)
Description  : Cache files between runs
Version      : 0.1.0
Author       : Microsoft Corporation
Help         : https://aka.ms/pipeline-caching-docs
==============================================================================
Resolving key `D:\a\1\s/package-lock.json`...
##[error]No files found.
##[debug]Processed: ##vso[task.logissue type=error;]No files found.
##[debug]Processed: ##vso[task.complete result=Failed;]
##[debug]   at Agent.Plugins.PipelineCache.FingerprintCreator.EvaluateKeyToFingerprint(AgentTaskPluginExecutionContext context, String filePathRoot, IEnumerable`1 keySegments)
   at Agent.Plugins.PipelineCache.PipelineCacheTaskPluginBase.RunAsync(AgentTaskPluginExecutionContext context, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
##[section]Finishing: Cache npm
```

So even though the YAML was identical, the way the YAML is constructed seems to affect how the caching works. In looks like in the former, the key is treated as a string, but in the latter, it is treated as a file path.

Is this a known issue?

**Comment by MisinformedDNA** [comment]
I take it back, only the former scenario is happening now. For some reason, the key was being treated as a string and now it is being treated as a file path. But this is what I really want anyway, right? How does the agent know how to treat the key?

**Comment by MisinformedDNA** [comment]
Running a similar issue:

I want the key to use a variable, but it's using the variable name instead:

```yaml
- pwsh: |
    $hashes = (gci -File -Recurse | Get-FileHash).Hash
    $combinedHash = $hashes -join ' '
    echo "##[task.setvariable variable=SuperHash]$combinedHash"

- task: CacheBeta@0
  displayName: Get NuGet packages from cache
  inputs:
    key: |
      $(SuperHash)
    path: $(UserProfile)/.nuget/packages
```

Task output:
```
Resolving key `$(SuperHash)`...
Resolved to `$(SuperHash)`.
##[debug]Processed: ##vso[task.settaskvariable variable=RESTORE_STEP_RAN;issecret=False;]true
##[debug]Dedup parallelism: 192
Information, Getting a pipeline cache artifact with one of the following fingerprints:
Information, Fingerprint: `$(SuperHash)`
Information, There is a cache hit: `$(SuperHash)`
```

**Comment by ronaldbarendse** [comment]
@MisinformedDNA You're not correctly setting the variable (it should start with `##vso`): https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-in-script
