### ISSUE TITLE
Bug: ubuntu-latest (ubuntu-18.04) stopped working

### ISSUE THREAD

**Issue by guibirow** [microsoft/azure-pipelines-yaml#379]
Hi All,

Today we noticed our build pipelines stopped working when running the command `dotnet restore -v diag` step when using `ubuntu-latest` image, with message `The FileName property should not be a directory unless UseShellExecute is set`.  This was working fine until last week and no changes has been made to the code, previously working commit were also affected and don't build anymore.

To ensure it was an agent issue, ee change the image `ubuntu-latest` to `ubuntu-16.04` the build goes back to normal.

Below is the error found in the logs:

```
2019-11-04T11:40:43.0124525Z MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
2019-11-04T11:40:43.0143371Z Microsoft.Build.BackEnd.NodeFailedToLaunchException: The FileName property should not be a directory unless UseShellExecute is set. ---> System.ComponentModel.Win32Exception: The FileName property should not be a directory unless UseShellExecute is set.
2019-11-04T11:40:43.0143506Z    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
2019-11-04T11:40:43.0143546Z    at System.Diagnostics.Process.Start()
2019-11-04T11:40:43.0143631Z    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
2019-11-04T11:40:43.0143670Z    at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
2019-11-04T11:40:43.0143929Z    --- End of inner exception stack trace ---
2019-11-04T11:40:43.0144021Z    at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
2019-11-04T11:40:43.0144302Z    at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.GetNode(String msbuildLocation, String commandLineArgs, Int32 nodeId, INodePacketFactory factory, Int64 hostHandshake, Int64 clientHandshake, NodeContextTerminateDelegate terminateNode)
2019-11-04T11:40:43.0144437Z    at Microsoft.Build.BackEnd.NodeProviderOutOfProc.CreateNode(Int32 nodeId, INodePacketFactory factory, NodeConfiguration configuration)
2019-11-04T11:40:43.0144543Z    at Microsoft.Build.BackEnd.NodeManager.AttemptCreateNode(INodeProvider nodeProvider, NodeConfiguration nodeConfiguration)
2019-11-04T11:40:43.0144581Z    at Microsoft.Build.BackEnd.NodeManager.CreateNode(NodeConfiguration configuration, NodeAffinity nodeAffinity)
2019-11-04T11:40:43.0144618Z    at Microsoft.Build.Execution.BuildManager.PerformSchedulingActions(IEnumerable`1 responses)
2019-11-04T11:40:43.0144701Z    at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
2019-11-04T11:40:43.0144745Z    at Microsoft.Build.Execution.BuildManager.ProcessPacket(Int32 node, INodePacket packet)
2019-11-04T11:40:43.0144783Z    at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass67_0.<Microsoft.Build.BackEnd.INodePacketHandler.PacketReceived>b__0()
2019-11-04T11:40:43.0144871Z    at Microsoft.Build.Execution.BuildManager.ProcessWorkQueue(Action action)
2019-11-04T11:40:43.0145180Z --- End of stack trace from previous location where exception was thrown ---
2019-11-04T11:40:43.0145221Z    at Microsoft.Build.Execution.BuildManager.EndBuild()
2019-11-04T11:40:43.0145327Z    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
2019-11-04T11:40:43.0145366Z 
2019-11-04T11:40:43.0165880Z MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
2019-11-04T11:40:43.0166790Z Microsoft.Build.BackEnd.NodeFailedToLaunchException: The FileName property should not be a directory unless UseShellExecute is set. ---> System.ComponentModel.Win32Exception: The FileName property should not be a directory unless UseShellExecute is set.
2019-11-04T11:40:43.0166995Z    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
2019-11-04T11:40:43.0167043Z    at System.Diagnostics.Process.Start()
2019-11-04T11:40:43.0167086Z    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
2019-11-04T11:40:43.0167186Z    at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
2019-11-04T11:40:43.0167514Z    --- End of inner exception stack trace ---
2019-11-04T11:40:43.0167605Z    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
2019-11-04T11:40:43.0167715Z    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
2019-11-04T11:40:43.0167960Z [91m
2019-11-04T11:40:43.0168540Z Unhandled Exception: [0m[91mMicrosoft.Build.BackEnd.NodeFailedToLaunchException: The FileName property should not be a directory unless UseShellExecute is set. ---> System.ComponentModel.Win32Exception: The FileName property should not be a directory unless UseShellExecute is set.
2019-11-04T11:40:43.0168797Z    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
2019-11-04T11:40:43.0168898Z    at System.Diagnostics.Process.Start()
2019-11-04T11:40:43.0169020Z    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
2019-11-04T11:40:43.0169071Z    at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
2019-11-04T11:40:43.0169381Z    --- End of inner exception stack trace ---
2019-11-04T11:40:43.0169522Z    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
2019-11-04T11:40:43.0169640Z    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
2019-11-04T11:40:43.0169686Z    at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
2019-11-04T11:40:49.8088358Z [0mThe command '/bin/sh -c dotnet restore' returned a non-zero code: 134
```

**Comment by guibirow** [comment]
Adding this reference, because looks like this is a kernel 5.0 issue. Probably the agent has been upgraded.

https://github.com/dotnet/core/issues/3309

**Comment by rainersigwald** [comment]
This should be fixed and deployed. For details, see actions/virtual-environments#2 (that's GitHub Actions, but they share Linux kernel version with Azure Pipelines hosted environments).
